### ISSUE TITLE
Cannot support "Go to definition" for the same keyword with a dot splitting 

### ISSUE THREAD

**Issue by virtualnode** [tomi/vscode-rf-language-server#15]
Prepared 3 robot files (including  2 resource files for save keywords, and 1 for save test suites).
There is a same keyword "input" in both text.robot and textarea.robot. And then in test_suites.robot editing in VSCode, the F12 doesn't work to the keyword "text.input" or "textarea.input" any more.
------------

text.robot

------------

    *** Keywords ***
    Input
    	[Arguments]	${id}	${value}
    	[Documentation]	Input in textbox。
    	Log		Text Input

------------

textarea.robot

------------

    *** Keywords ***
    Input
    	[Arguments]	${id}	${value}
    	[Documentation]	Input in text area。
    	Log		Text Area Input

------------

test_suites.robot

------------

    *** Settings ***
    *** Variables ***
    *** Test Cases ***
    A demo test
    	text.input	id1hello, text!
    	textarea.input	id2 hello, text area!

------------

**Comment by tomi** [comment]
Support added in version 2.1.1
