### ISSUE TITLE
Python keywords?

### ISSUE THREAD

**Issue by PositiveAlex** [tomi/vscode-rf-language-server#2]
Hi!

If I defined a custom library on python, how to show this library for your plugin? 
All python code is in the PYTHONPATH so for instance, pycharm normally parsing those custom keywords in robot file but your plugin don't.

**Comment by tomi** [comment]
Hi,

Python libraries are not yet supported, but this is something I plan to support later on.

**Comment by PositiveAlex** [comment]
Big thanks, mate.

**Comment by tomi** [comment]
With the release of version 0.8.0, the extension now supports also python keywords. Just set the setting `rfLanguageServer.pythonKeywords` to `true`.
