### ISSUE TITLE
Code completion for standard libraries

### ISSUE THREAD

**Issue by JaPyR** [tomi/vscode-rf-language-server#21]
Hello, is it possible to have code completion for keywords from standard libraries and for libraries added using Library keyword?

**Comment by lubosjerabek** [comment]
Just saying - this definitely gets my vote as well. Huge help, Sublime Text plugin supports the same thing actually.

**Comment by tomi** [comment]
I'm happy to announce that this is now implemented in the latest version 2.2.0!
