### ISSUE TITLE
File name is added to user keyword while searching keywords

### ISSUE THREAD

**Issue by timmy8526** [tomi/vscode-rf-language-server#29]
I update the extension yesterday from 2.0.1 to 2.2.0.
Then I found that searching keyword function seems broken. 
It will add the robot file name into my user keywords as prefix, which make my user keyword not working, and I need to manually remove these prefixes again and again.

For example:
A keyword named:  **Userkeyword: Do something** in **User** file
I will get **User.Userkeyword: Do something** instead of **Userkeyword: Do something** while searching keywords.

NOTE: I tested it on 2.1.1 and 2.2.0, both can reproduce this issue.

**Behavior on 2.0.1 (work perfectly)**
![2 0 1_work_fine](https://user-images.githubusercontent.com/13176540/47479712-8c78ff00-d860-11e8-829d-f4117f2fe89d.jpg)

**Behavior on 2.2.0 / 2.1.1 (wrong keyword)**
![versoin_greater_than_2 0 1](https://user-images.githubusercontent.com/13176540/47479722-91d64980-d860-11e8-8c08-a225ea85eead.jpg)

**Comment by tomi** [comment]
You're right, this is an annoying bug. Need to fix it

**Comment by tomi** [comment]
Fixed in 2.2.1
