### ISSUE TITLE
OUTPUT console keep popping up with error while typing "..."

### ISSUE THREAD

**Issue by timmy8526** [tomi/vscode-rf-language-server#32]
#### Description
Update extension to 2.2.1 today, and the OUTPUT console of VSCode keep popping up while I was trying to typing "..." to wrap lines for long keyword arguments. Which is very annoying and I cannot find a way to disable it.

![image](https://user-images.githubusercontent.com/13176540/48388369-0ac81300-e734-11e8-94ae-5b3bbbe492db.png)

#### Environment: 
 - VS Code: 1.29.0
 - Robot Framework Intellisense: 2.2.1

**Comment by tomi** [comment]
This should be fixed in the version 2.3.0
