### ISSUE TITLE
Supporting other editors besides vscode ?

### ISSUE THREAD

**Issue by rasjani** [tomi/vscode-rf-language-server#34]
This is really not a bug report nor a question or possible feature request.

Many other editors besides vscode also support language server protocols (köhvimköh) so i was wondering if  this project (without the client) is cabable of also interacting with any other editors?  Has it been tried ? If it not possible, any estimates about how much work it would be?

**Comment by tomi** [comment]
Yes, this project uses the [Language Server Protocol](https://microsoft.github.io/language-server-protocol/) and is implemented with [VSCode Language Server](https://github.com/Microsoft/vscode-languageserver-node). It consists of a client and server, and the server is completely standalone Node.js server. Is is possible to take just the server and with your own client integrate that to another editor. I have not tried it tho, and it I guess it depends how much work that is. For example does the other editor support the language server protocol out of the box, is there a ready made client for you editor you can use to integrate it with the server, how hard is it to make plugins for the other editor etc.

**Comment by rasjani** [comment]
Client side things are not really concern for me as there is generic plugin for vim that implements the protocol.  

I guess my real question is: how “stand-alone” this implementation is in regards to dependency towards vscode ?

**Comment by tomi** [comment]
The server has no dependency to vscode. The only thing you need to run it is Nodejs.

**Comment by Snooz82** [comment]
@tomi 
Can you give a hint how to start the Server as "stand Alone" with nodeJS?

i want to give it a try.
We in the board of Robot Framework Foundation want to develop a Language Server for "all" Editors in the future. And you did already quite a good job!

Can you help me a bit with this issue?

Tanks.

**Comment by tomi** [comment]
Hi @Snooz82 

I made couple small changes and now with these steps you should be able to start the language server:

```
cd server
npm install
npm run build
node out/server.js
```

This starts the server using stdin and stdout for the transport. Other transports can be used by giving params `--node-ipc` or `--socker={number}`. Hopefully this helps you.

My original plan has always been to publish the parser as an NPM package, but I haven't done it yet. It would be possible to publish also the language server as an NPM package, so it could be easily installed with NPM.

**Comment by rasjani** [comment]
i know this is not issue really about vscode-rf-language-server but id like to make comment.. Imho, if the langserv requires different runtime as rf itself, there will be issue about adopting it for general use.

**Comment by Snooz82** [comment]
Hi Jani,

I know that using a NodeJS Language Server is not a solution. We need a Python Solution. 

But i want to give it a try to see if this could be a workaround for the meantime.
The VSCode integration of Tomi is imho (except the RED for Eclipse) one of the best plugins for editors. 

An i like Pycharm but the Robot integration is odd and outdated.

I want to see how it feels and if this is the way to go for the future.

As i remembered you volunteered as a Developer for the Python Language Server, right? 😉

**Comment by Snooz82** [comment]
Thanks Tomi!

**Comment by rasjani** [comment]
@tomi are you on rf slack ? If yes, could you join to #lsp channel?
