### ISSUE TITLE
Support for .resource robot framework files

### ISSUE THREAD

**Issue by sd-yazzoom** [tomi/vscode-rf-language-server#47]
**Is your feature request related to a problem? Please describe.**
Since version 3.1 of the Robot Framework, robot tests can also have the .resource extension (additional to the already supported .robot and .txt extensions). .resource files are formatted exactly the same as .robot files, but can be used to make a difference between test files and resources called in these robot test files.

When adding these resource files in the plugin's included paths, they currently seem to be ignored (documentation also mentions it only looks at robot and txt file extensions)

**Describe the solution you'd like**
Please add .resource file support (or maybe all file types associated to robot in vs code?). I think it might be a very small change since the content is identical to robot files.

Note that the resource declarations may also include .resource at the end. 
E.g.:
Resource  ../path/MyResource.resource

**Describe alternatives you've considered**
I could rename my files to .robot, but really would like to make a distinction between robot framework test and resource files

**Comment by BabyMaybe** [comment]
Would also like to request support for this. Having the .resource and .robot files differentiate between tests and page objects or other resources is something I would really like to be able to maintain, and having the plugin support would significantly improve my life maintaining our existing codebase.

**Comment by BabyMaybe** [comment]
Digging around in the extension folder I did find that adding .resource to the server.js file with the same settings as .robot made it start working for me.

```
const parsersByFile = new Map([
    [".robot", robot_file_1.createRobotFile],
    [".resource", robot_file_1.createRobotFile],
    [".txt", robot_file_1.createRobotFile],
    [".py", python_file_1.createPythonFile],
]);
```

This is line 28 of .vscode/extensions/tomiturtiainen.rf-intellisense-2.5.0/server/server.js on Ubuntu.

I don't see a comparable file in the repo or I'd open up a PR for it. I'm assuming this is a generated file, but if so there must be a similar line somewhere else in the codebase.

**Comment by sd-yazzoom** [comment]
> Digging around in the extension folder I did find that adding .resource to the server.js file with the same settings as .robot made it start working for me.
> 
> ```
> const parsersByFile = new Map([
>     [".robot", robot_file_1.createRobotFile],
>     [".resource", robot_file_1.createRobotFile],
>     [".txt", robot_file_1.createRobotFile],
>     [".py", python_file_1.createPythonFile],
> ]);
> ```
> 
> This is line 28 of `.vscode/extensions/tomiturtiainen.rf-intellisense-2.5.0/server/server.js` on Ubuntu.
> 
> I don't see a comparable file in the repo or I'd open up a PR for it. I'm assuming this is a generated file, but if so there must be a similar line somewhere else in the codebase.

Found it in the src folder in the repository, so vscode/extensions/tomiturtiainen.rf-intellisense-2.5.0/server/src/server.js .

**Comment by venkateshkonduru1** [comment]
Same I have repeated on windows, in server.js still ".resource" is not working as .robot file

**Comment by BabyMaybe** [comment]
I did a PR here
https://github.com/tomi/vscode-rf-language-server/pull/50

After you make the changes you need to add .resource to your file associations and include paths as well in your vscode settings file
```
 "files.associations": {
  ...
 "*.resource": "robot"
 },
 "rfLanguageServer.includePaths": [
  ...
 "**/*.resource",
 ],
```

**Comment by venkateshkonduru1** [comment]
I don't find file.association in settings.json file

**Comment by BabyMaybe** [comment]
If that setting isn't there it just means you haven't added any custom associations yet. You can either add it manually or on the bar at the bottom right if you click where it says Plain Text it will bring up an option to select a file format, and you can scroll down to Robot Framework from there and that will add it automatically.

More details here.
https://code.visualstudio.com/docs/languages/overview

**Comment by tomi** [comment]
Hi and thank you for filing this issue. The support has been added in latest version 2.6.0.
