### ISSUE TITLE
Does not handle data driven test format

### ISSUE THREAD

**Issue by Zeff** [tomi/vscode-rf-language-server#5]
When using a data driven test format as indicated by referencing a Test Template, all one line test cases are formatted as one long test case name as opposed to the first item being the name, the rest being arguments that are passed to the template for that test case.

It may actually function (I didn't test it ... stopped when I couldn't read it), but it's extremely uncomfortable to look at, edit, or write when the entire line is highlighted and underlined as a test case name.

But thanks for the good work so far. Looks very promising!

**Comment by tomi** [comment]
Thank you for filing an issue! The way a test case name is identified for syntax highlighting is at the moment subpar. The highlighting should be an easy fix. The parser however doesn't yet understand the `[Template]` setting nor test cases that use a template, so for example goto definition might not work correctly with them.

**Comment by tomi** [comment]
I just released a version 0.7.0 that should fix the highlighting issue. Please give it a go and let me know if it still doesn't work as expected.

**Comment by Zeff** [comment]
Looks good to me, Tomi! Thanks so much!
