### ISSUE TITLE
Defining 3rd party libraries doesn't support Chinese keywords

### ISSUE THREAD

**Issue by virtualnode** [tomi/vscode-rf-language-server#52]
**Describe the bug**

**To Reproduce**
1. Go to 'Settings.json and edit'
2. Add following to the json:
"rfLanguageServer.libraries": [
        {
          "name": "MyLibrary",
          "version": "1.0.0",
          "keywords": [
            { "name": "My Keyword 1", "args": ["arg1"], "doc": "documentation" },
            { "name": "My Keyword 2", "args": [],       "doc": "documentation" },
            { "name": " 做个测试", "args": ["arg1"], "doc": "documentation" },
          ]
        }
      ]
3. Create a Test.robot and edit, when type 'My Ke', the keywords works for the first 2. But when typing '做个'， the last keyword "做个测试“doesn't be shown.

**Expected behavior**
Should have suggestion of the keyword with Chinese Character '做个测试' while typing '做个'

**Screenshots**

**Environment (please complete the following information):**
 - VSCode version: 1.33.1
 - Extension version: 2.5.0
 - OS: [e.g. Linux/Mac/Win]
windows 10
**Extension output:**
Please include the extension output with debug logging turned on.
1. Add setting `"rfLanguageServer.logLevel": "debug"`
1. Select View -> Output -> Robot Framework Intellisense Server
1. Reproduce the issue

**Additional context**

**Comment by tomi** [comment]
You have a space in the beginning of your keyword name. If you remove it, the suggestion is shown correctly.

Maybe the keyword names should be trimmed when they are parsed to prevent thus kind of issues.
