### ISSUE TITLE
Repository Link in VSCode Ext page not working

### ISSUE THREAD

**Issue by jthegedus** [tomi/vscode-rf-language-server#57]
**Describe the bug**
Link does not link to the repo.

**To Reproduce**
See screenshot below and try clicking `repository`.

**Expected behavior**
Open link to the repo.

**Screenshots**
<img width="1023" alt="Screen Shot 2019-08-16 at 3 37 05 pm" src="https://user-images.githubusercontent.com/20798510/63145694-c14a8280-c03b-11e9-9600-b3239cab9435.png">

**Environment (please complete the following information):**
 - VSCode version: 1.37.1
 - Extension version: 2.6.0
 - OS: macOS

**Comment by tumit** [comment]
Can I take this issue ?
